/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fop;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import com.opencsv.exceptions.CsvException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        ItemDao itemDao = new ItemDao();

        try (Reader reader = Files.newBufferedReader(Paths.get("csv/item.csv"));) {
            List<Item> items = itemDao.read(reader);
            for (Item item : items) {
                System.out.println(item.getId());
                System.out.println(item.getName());
                System.out.println(item.getPrice() * item.getAmount());
            }
        } catch (IOException e) {
            System.out.println("指定されたCSVファイルがありません。");
            e.printStackTrace();
        } catch (CsvException e) {
            System.out.println("CSVファイルが不正です。");
            e.printStackTrace();
        }
    }
}
